version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    command: ./scripts/docker-entrypoint.sh
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      mongo:
        condition: service_healthy
    links:
      - mongo

volumes:
  mongo-data:
    driver: local
